---
- name: "configuration play."
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600

    - name: "install python for Ansible."
      become: true
      apt:
        name: "python3"
        state: latest
        update_cache: yes

  # B2. Configure Infrastructure (1.b)
  # Get the environment variables from CircleCI and add to the EC2 instance
  # Object–relational mapping to create virtual object database
  # https://en.wikipedia.org/wiki/Object%E2%80%93relational_mapping
  # https://typeorm.io/

  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/env_lookup.html
  # https://docs.ansible.com/ansible/latest/plugins/lookup.html

  tasks:
  # B2. Configure Infrastructure (1.b)
  # Keep your playbook clean and maintainable by using roles.
  # You will need to decide what roles to create and how to split up your code.

  # In one of the roles
  ## Install Python (already done in pre_tasks here)
  ## Update/upgrade packages
  ## Install nodejs, npm, and pm2

  # Tips:
  ## Read project/.circleci/ansible/roles/configure-server/tasks/readme.md
  roles:
    - configure-server
