---
# Install required
- name: "update and upgrade packages."
  become: true
  apt:
    update_cache: yes
    upgrade: yes

- name: "remove undedependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# Install n for node version management
- name: "install n"
  become: true
  npm:
    name: n
    global: yes
    production: yes

# install/specify project recommended NodeJS version
- name: "specify nodejs 13.8.0"
  become: true
  shell: n 13.8.0

# Use ansible to copy the files
# In the "deploy" role, you can extract the zipped artifact into the EC2 instance, and then start the app.

# backend directory zipped in home directory
# using Tape ARchive
# in deploy-backend job in .circleci/config.yml

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html
# unarchive module src different from dest does the copying
# unarchive does the extracting

- name: "extract the zipped artifact into the EC2 instance"
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "start app"
  become: true
  shell: |
    npm install  
    pm2 stop default  
    sudo pm2 start npm -- start
